ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS equipped_lives       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equipped_hammers     INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equipped_shields     INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equipped_xp_booster  INTEGER NOT NULL DEFAULT 0;
